global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'api-metrics'
    metrics_path: /api/metrics
    scheme: https
    static_configs:
      - targets:
          - sneaker-tracker-api.vercel.app

  - job_name: 'blackbox-api'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://sneaker-tracker-api.vercel.app/api/health/ready
          - https://sneaker-tracker-api.vercel.app/api/health/details
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

rule_files:
  - /etc/prometheus/rules/alerts.yml
